export const GET_FONTS_LIST_FROM_GOOGLE_SUCCESS = 'GET_FONTS_LIST_FROM_GOOGLE_SUCCESS';
export const CHANGE_ADJUSTED_DATA = 'CHANGE_ADJUSTED_DATA';
export const CHANGE_SELECTED_COLOR = 'CHANGE_SELECTED_COLOR';
export const START_TEXT_EDIT = 'START_TEXT_EDIT';
export const CHANGE_EDITED_TEXT = 'CHANGE_EDITED_TEXT';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
