export const GET_FONTS_LIST_SUCCESS = 'GET_FONTS_LIST_SUCCESS';
export const OPEN_SIGN_UP_MODAL = 'OPEN_SIGN_UP_MODAL';
export const OPEN_UPLOAD_MODAL = 'OPEN_UPLOAD_MODAL';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const GET_FONT_DETAIL = 'GET_FONT_DETAIL';
export const AUTHENTICATE = 'AUTHENTICATE';
export const LOGOUT = 'LOGOUT';
